#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:          	chk_ctrl_files
#
# Description:          
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#	18-Feb-2003	1.0	oracle	Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh


EXITCODE=0

scriptname=$(basename ${0})
today=$(date +%Y%m%d)

tmpfile=/tmp/$scriptname.$$
sqlplus -s ${SQLPLUS_DBA_LOGON} << *EOF*  2>&1 > /dev/null
whenever sqlerror exit 4
set pages 0
set lines 132
set echo off
set feedback on
set termout on
spool $tmpfile
select decode(count(*), 1, 'CONTROL_FILE_COUNT:BAD', 'CONTROL_FILE_COUNT:GOOD')
from v\$controlfile;
exit
*EOF*
status=$?

if [ $status -ne 0 ]
then
    echo error: could not log on to database
    EXITCODE=1
fi

if [ "$(grep CONTROL_FILE_COUNT:BAD $tmpfile)" != "" ]
then
    echo error: Only one controlfile for this database
    EXITCODE=1
fi



[ -f $tmpfile ] && rm -f $tmpfile

exit $EXITCODE

