#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:          	chk_nontemp_temp_tspace
#
# Description:          
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#	18-Feb-2003	1.0	oracle	Original version
#
#+++___________________________________________________________________________________


EXITCODE=0

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh


if [ $# -ne 0 ]
then
    echo usage: $scriptname 
    exit 1
fi

if [ "$ORACLE_SID" = "" ] && [ "TWO_TASK" = "" ]
then
    echo error: ORACLE_SID and TWO_TASK not set
    exit 1
fi

sqlplus -s ${SQLPLUS_DBA_LOGON} << *EOF* 2>&1 > /dev/null
whenever sqlerror exit sql.sqlcode
set echo off
set termout off
set feedback off
set pages 0 lines 132
spool $tmpfile
select rpad(username, 32, ' ') || temporary_tablespace
from dba_users u,
     dba_tablespaces t
where u.temporary_tablespace = t.tablespace_name
  and t.contents != 'TEMPORARY';
spool off
exit
*EOF*
status=$?

if [ $status -ne 0 ]
then
    echo error: could not log on to check database
    EXITCODE=1
fi

if [ "$(cat $tmpfile)" != "" ]
then
    echo
    echo The following users have a non-TEMPORARY temporary tablespace
    echo
    cat $tmpfile | sed -e 's/^/        /'
    echo
    EXITCODE=1
fi

rm -f $tmpfile

exit $EXITCODE

