#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  gendfileebkup
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       18-Jul-2006     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

. /opt/dsp/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING=""


#
# Define local script variables
#

#
# Script starts here
#
#
set_error_trap

for file in ${*}
do
    echo $file | sed -e "s/.*/alter database datafile '&' begin backup;/" 
done


exit $EXITCODE

