#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:          	getccfhead
#
# Description:          
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#	27-Feb-2003	1.0	oracle	Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.env

EXITCODE=0

scriptname=$(basename ${0})
today=$(date +%Y%m%d)
tmpfile=/tmp/$scriptname.$$

if [ $# -ne 1 ]
then
    echo usage: ${scriptname} ccffile
    EXITCODE=1
    exit $EXITCODE
else
    CCFILE=${1}

    if [ ! -f ${CCFILE} ]
    then
	echo ERROR: $CCFILE does not exist
	EXITCODE=1
	exit
    fi
fi


awk '/^CREATE CONTROLFILE/,/^DATAFILE/' ${CCFILE}


[ -f $tmpfile ] && rm $tmpfile

exit $EXITCODE

