#!/bin/bash
set +x

#+++___________________________________________________________________________________
#
#
# Script name:                  getdbversion
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       01-Oct-2003     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh


USAGE_STRING="[-c] [-d SID[:pdb]] [-h host] [-z]"

#DEBUG=YES

#
# Script starts here
#
#
#set_error_trap

INTERACTIVE_SHELL="YES"
while getopts 'd:h:xz' OPTION
do
    case "$OPTION" in
        c) SQL_NO_EXIT_ON_ERROR=YES ;;
        d) db=$OPTARG ; unset ORACLE_PDB_SID ; unset DSP_PDB_SID ;; 	# if -d parameter then clear any PDB env references
        h) dbhost=$OPTARG ;;
        z) INTERACTIVE_SHELL="NO" ;;
        ?) usage ;;
    esac
done
shift $((OPTIND-1))

if [ $# -gt 0 ]
then
    usage
fi


db=${db:-$ORACLE_SID}	# set to ORACLE_SID if not set from command line -d option

if [ "${dbhost}" != "" ]
then
    : # run on different host
else
   :  # run on this host
   export ORACLE_SID=$(echo ${db} | awk -F: '{print $1}')

   if [ "${ORACLE_SID}" = "" ]
   then
        echo ERROR: ORACLE_SID is null
        EXITCODE=1
        exit $EXITCODE
   fi

   if chkoradbinoratab ${ORACLE_SID}
   then
       :
   else
       echo "ERROR: $ORACLE_SID not in [${ORATAB}]"
       EXITCODE=1
       exit ${EXITCODE}
   fi

   . /usr/local/bin/oraenv 2>&1 > /dev/null

   if chkoradbopen $ORACLE_SID 
   then
       :
   else
       echo "ERROR: $ORACLE_SID is not up"
       EXITCODE=1
       exit ${EXITCODE}
   fi

   SQL_EXIT_ON_ERROR=${SQL_EXIT_ON_ERROR:-YES}
   if [ "${SQL_EXIT_ON_ERROR}" != "NO" ]
   then
	SQL_WHENERROR="exit sql.sqlcode"
   else
	SQL_WHENERROR="continue"
   fi

    if [ "${INTERACTIVE_SHELL}" = "YES" ]
    then
        sqlplus_set_cmd="set pagesize ${SQLPLUS_PAGESIZE} linesize ${SQLPLUS_LINESIZE} echo on feedback on termout on"
    else
        sqlplus_set_cmd="set pagesize 0 linesize 140 echo off feedback off verify off"
    fi

VERSION=$(sqlplus -s ${SQLPLUS_DBA_LOGON} << *EOF* 2>&1 | grep ^VERSION: | cut -d: -f2 
whenever sqlerror ${SQL_WHENERROR}
${sqlplus_set_cmd}
select 'VERSION:' || product || ' ' ||version_full
from PRODUCT_COMPONENT_VERSION
where lower(product) like 'oracle database%';
exit
*EOF*
)

if [ "${VERSION}" = "" ]
then
VERSION=$(sqlplus -s ${SQLPLUS_DBA_LOGON} << *EOF* 2>&1 | grep ^VERSION: | cut -d: -f2 
whenever sqlerror ${SQL_WHENERROR}
${sqlplus_set_cmd}
select 'VERSION:' || product || ' ' ||version
from PRODUCT_COMPONENT_VERSION
where lower(product) like 'oracle database%';
exit
*EOF*
)
fi
echo ${VERSION}
status=$?

# if MAJOR_VERSION <= 12.1.0.2 (inclusive) then just VERSION from PRODUCT_COMPONENT_VERSION
# https://christian-gohmann.de/2020/02/27/different-ways-to-get-the-current-database-version/#PRODUCT_COMPONENT_VERSION



fi	#dbhost
    

if [ "${INTERACTIVE_SHELL}" = "YES" ]
then
   # blank line before returning prompt
    echo ""
fi

exit $EXITCODE

