#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  getinfo-orahome
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       22-Oct-2025     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=/opt/dsp
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING="[-o ORACLE_HOME] [-m lite|basic|comp] [-s human|machine]"

mode="lite"
style="human"

while getopts 'd:o:m:s:' OPTION
do
    case "$OPTION" in
        d) osid=$OPTARG ;;
        o) ohome=$OPTARG ;;
        m) mode=$OPTARG ;;
        s) style=$OPTARG ;;
        ?) usage ;;
    esac
done

if [ "${osid}" != "" ] && [ "${ohome}" != "" ]
then
    echo "ERROR: cannot using -d and -o options concurrently - exiting"
    EXITCODE=1
    exit ${EXITCODE}
fi

if [ "${osid}" != "" ]
then
    export ORACLE_SID=${osid}
    export ORAENV_ASK=NO
    . ${ORAENV}
else
    if [ "${ohome}" != "" ]
    then
        export ORACLE_HOME=${ohome}
    fi
fi

if [ "${ORACLE_HOME}" = "" ]
then
    echo "ERROR: ORACLE_HOME not set - exiting"
    EXITCODE=1
    exit ${EXITCODE}
fi

if [ ! -d ${ORACLE_HOME} ]
then
    echo "ERROR: ORACLE_HOME [${ORACLE_HOME}] set but is not a directory - exiting"
    EXITCODE=1
    exit ${EXITCODE}
fi

case "${mode}" in
    [lL][iI][tT][eE] ) mode=lite ;;
    [bB][aA][sS][iI][cC] ) mode=basic ;;
    [cC][oO][mM][pP] ) mode=comp ;;
    *) echo "ERROR: invalid mode [${mode}] - exiting" ; exit 1 ;;
esac

case "${style}" in
    [hH][uU][mM][aA][nN]) style=human;;
    [mM][aA][cC][hH][iI][nN][eE]) style=machine;;
    *) echo "ERROR: invalid style [${style}] - exiting" ; exit 1 ;;
esac

if [ "${ORACLE_HOME}" = "" ]
then
    echo "ERROR: ORACLE_HOME not set and not passed via command line - exiting"
    exit 1
fi


if [ ! -d ${ORACLE_HOME} ]
then
   echo "ERROR: ${ORACLE_HOME} does not exist - exiting"
   exit 1
fi

typeset -i lvl
typeset -i level


export PATH=${ORACLE_HOME}/OPatch:${ORACLE_HOME}/bin:${PATH}

function print_begin
    {
    padding=""
    lvl=1
    while [ ${lvl} -lt ${level} ]
    do
        padding="    ${padding}"
        let lvl=${lvl}+1
    done

    if [ "${style}" = "human" ]
    then
        echo "${padding}---------------------------------------------------"
        echo "${padding}${1}"
        echo "${padding}---------------------------------------------------"
    else
        echo "${padding}<BEGIN_${1}>"
    fi
    }


function print_end
    {
    padding=""
    lvl=1
    while [ ${lvl} -lt ${level} ]
    do
        padding="    ${padding}"
        let lvl=${lvl}+1
    done

    if [ "${style}" = "human" ]
    then
        echo ""
    else
        echo "${padding}<END_${1}>"
    fi
    }


function show_databases
    {
    if [ "${style}" = "human" ]
    then
        level=$1
        TAG=DATABASES

        print_begin ${TAG}

        padding="    ${padding}"
    else
        echo "<databases>"
        padding=""
    fi

    for DB in $(awk -F: -v v_ohome=${ORACLE_HOME} '$2==v_ohome {print $1}' ${ORATAB} | grep ^[a-zA-Z0-9_$] | sort)
    do
        echo -n "${padding}${DB}:"

        if isinstup ${DB} 2>&1 > /dev/null
        then
            instance_status=$(${scriptdir}/sqlx -d ${DB} select \'STATUS=\' \|\| status from v\$instance 2>/dev/null | grep ^STATUS= | cut -d= -f2)

            [ "${instance_status}" = "STARTED" ] && instance_status="NOMOUNT"
        else
            instance_status="DOWN"
        fi

        echo "instance:${instance_status}"
    done

    if [ "${style}" = "human" ]
    then
        print_end ${TAG}
    else
        echo "</databases>"
    fi
    }

function show_java
    {
    level=$1
    TAG=JAVA


    if [ "${style}" = "human" ]
    then
        print_begin ${TAG}

        let level=$level+1
        TAG=JDK

        print_begin ${TAG}
    
        padding="    ${padding}"

        # java -version output seems to go to stderr therefore need to 
        # redirect to stdout otherwise the pipe in to sed does not work
        # resulting in no indentation

        $ORACLE_HOME/jdk/bin/java -version 2>&1 | sed -e "s/^/${padding}/"

        echo
    else
        echo "<java_jdk>"
        $ORACLE_HOME/jdk/bin/java -version
        echo "</java_jdk>"
    fi

    if [ "${style}" = "human" ]
    then
        TAG=JRE

        print_begin ${TAG}

        padding="    ${padding}"

        # java -version output seems to go to stderr therefore need to 
        # redirect to stdout otherwise the pipe in to sed does not work
        # resulting in no indentation

        $ORACLE_HOME/jdk/jre/bin/java -version 2>&1 | sed -e "s/^/${padding}/"

        echo

        print_end ${TAG}
    else
        echo "<java_jre>"
        $ORACLE_HOME/jdk/jre/bin/java -version
        echo "</java_jre>"
    fi
    }

function show_perl
    {
    level=$1
    TAG=PERL

    if [ "${style}" = "human" ]
    then
        print_begin ${TAG}
        padding="    ${padding}"
        $ORACLE_HOME/perl/bin/perl -v | sed -e "s/^/${padding}/"
        print_end ${TAG}
    else
        echo "<perl>"
        $ORACLE_HOME/perl/bin/perl -V
        echo "</perl>"
    fi
    }

function show_opatch_version
    {
    if [ "${style}" = "human" ]
    then
        level=$1
        TAG=OPATCH_VERSION
    
        print_begin ${TAG}
    
        padding="    ${padding}"
        ${ORACLE_HOME}/OPatch/opatch version | sed -e "s/^/${padding}/"
        status=$?
    
        print_end ${TAG}
    else
        echo "<opatch_version>"
        ${ORACLE_HOME}/OPatch/opatch version | sed -e "s/^/${padding}/"
        echo "</opatch_version>"
    fi
    }


function show_opatch_lspatches
    {
    if [ "${style}" = "human" ]
    then
        level=$1
        TAG=OPATCH_LSPATCHES
    
        print_begin ${TAG}
    
        padding="    ${padding}"
        ${ORACLE_HOME}/OPatch/opatch lspatches | sed -e "s/^/${padding}/"
        status=$?
    
        print_end ${TAG}
    else
        echo "<opatch_lspatches>"
        ${ORACLE_HOME}/OPatch/opatch lspatches | sed -e "s/^/${padding}/"
        echo "</opatch_lspatches>"
    fi
    }


function show_opatch_lsinventory
    {
    if [ "${style}" = "human" ]
    then
        level=$1
        TAG=OPATCH_LSINVENTORY
    
        print_begin ${TAG}
    
        padding="    ${padding}"
        ${ORACLE_HOME}/OPatch/opatch lsinventory | sed -e "s/^/${padding}/"
        status=$?
    
        print_end ${TAG}
    else
        echo "<opatch_lsinventory>"
        ${ORACLE_HOME}/OPatch/opatch lsinventory | sed -e "s/^/${padding}/"
        echo "</opatch_lsinventory>"
    fi
    }


#
# Define local script variables
#

#
# Script starts here
#
#
set_error_trap

if [ "${style}" = "human" ]
then
    level=1
    TAG="ORACLE HOME (Oracle Database)"
    
    print_begin "${TAG}"
    
    padding="    ${padding}"
    echo "${padding}LOC: ${ORACLE_HOME}"
    echo 
else
    echo "<getinfo:oracle_home_database>"
    echo "timestamp:$(date +%Y%m%d%H%M%S)"

    echo "DSP_DISTRO:${DSP_DISTRO}"
    echo "DSP_WHOAMI:${DSP_WHOAMI}"
    echo "hostname:${HOSTNAME}"
    echo "dspserverid:${dspserverid}"

    if [ -r ${DSP_VERSION_FILE} ]
    then
        echo "dsp_version:$(cat ${DSP_VERSION_FILE})"
    else
        echo "dsp_version:file_not_found"
    fi

    if serverstampcheck 2>&1 > /dev/null
    then
        echo "serverstampcheck:PASS"
    else
        echo "serverstampcheck:FAIL"
    fi

    echo "<dsp_identity_file>"
    if [ -r ${DSP_IDENTITY_FILE} ]
    then
        grep -v ^\$ ${DSP_IDENTITY_FILE}
        status=$?
    else
        echo "error:file_not_found"
    fi
    echo "</dsp_identity_file>"

    echo "<details>"
    echo "loc:${ORACLE_HOME}"
fi

(
#
# run in subshell so as not to interfere with
# TAG setting as each of the functions below
# set TAG and without subshell
show_databases 2
show_java 2
show_perl 2
show_opatch_version 2
show_opatch_lspatches 2

if [ "${mode}" = "comp" ]
then
    show_opatch_lsinventory 2
fi
)

if [ "${style}" = "human" ]
then
    print_end ${TAG}
else
    echo "</details>"

    echo "</getinfo:oracle_home_database>"
fi

exit $EXITCODE

