#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  getinfo-oralsn
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       22-Oct-2025     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=/opt/dsp
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING="[-o ORACLE_HOME] [-m lite|basic|comp] [-s human|machine]"

listener=""
mode="lite"
style="human"

while getopts 'o:m:s:l:' OPTION
do
    case "$OPTION" in
        o) ORACLE_HOME=$OPTARG ;;
        l) listener=$OPTARG ;;
        m) mode=$OPTARG ;;
        s) style=$OPTARG ;;
        ?) usage ;;
    esac
done

case "${mode}" in
    [lL][iI][tT][eE] ) mode=lite ;;
    [bB][aA][sS][iI][cC] ) mode=basic ;;
    [cC][oO][mM][pP] ) mode=comp ;;
    *) echo "ERROR: invalid mode [${mode}] - exiting" ; exit 1 ;;
esac

case "${style}" in
    [hH][uU][mM][aA][nN]) style=human;;
    [mM][aA][cC][hH][iI][nN][eE]) style=machine;;
    *) echo "ERROR: invalid style [${style}] - exiting" ; exit 1 ;;
esac

if [ "${ORACLE_HOME}" = "" ]
then
    echo "ERROR: ORACLE_HOME not set and not passed via command line - exiting"
    exit 1
fi


if [ ! -d ${ORACLE_HOME} ]
then
   echo "ERROR: ${ORACLE_HOME} does not exist - exiting"
   exit 1
fi

typeset -i lvl
typeset -i level


export PATH=${ORACLE_HOME}/OPatch:${ORACLE_HOME}/bin:${PATH}

function print_begin
    {
    padding=""
    lvl=1
    while [ ${lvl} -lt ${level} ]
    do
        padding="    ${padding}"
        let lvl=${lvl}+1
    done

    if [ "${style}" = "human" ]
    then
        echo "${padding}${1}"
        echo "${padding}---------------------------------------------------"
    else
        echo "${padding}<BEGIN_${1}>"
    fi
    }


function print_end
    {
    padding=""
    lvl=1
    while [ ${lvl} -lt ${level} ]
    do
        padding="    ${padding}"
        let lvl=${lvl}+1
    done

    if [ "${style}" = "human" ]
    then
        echo ""
    else
        echo "${padding}<END_${1}>"
    fi
    }


function show_listener
    {
    level=$1
    TAG=LISTENER

    print_begin ${TAG}

    padding="    ${padding}"

    lsnrctl status ${listener}

    print_end ${TAG}
    }



#
# Define local script variables
#

#
# Script starts here
#
#
set_error_trap

level=1
TAG=ORACLE_LISTENER

print_begin ${TAG}

padding="    ${padding}"
echo "${padding}LOC: ${ORACLE_HOME}"
echo 

show_listener 2

print_end ${TAG}

exit $EXITCODE

