#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  hastempfiles
#
# Description:			This queries the version of Oracle and determines if the
#				database is at a version sufficient to use tempfiles
#				Oracle v7.x, v8.0.x did not use temporary files
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       04-Aug-2004     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

. /opt/dsp/env/dsp.env
. ${CS_TOP}/env/funcs.sh

WARN_ON_NONZERO_EXIT="NO"


#
# Script starts here
#
#
#set_error_trap

TEMPFILES_ARE_AVAILABLE=0
TEMPFILES_NOT_AVAILABLE=1

DBVERSION=$(dbversion ${*})
status=$?
check_status_exit "Encountered error determining database version"


DBVERSION_MAJOR=$(echo $DBVERSION | cut -d. -f1)
DBVERSION_MAJOR_MINOR=$(echo $DBVERSION | cut -d. -f-2)

if [ "${DBVERSION_MAJOR}" != "6" ] && [ "${DBVERSION_MAJOR}" != "7" ] && [ "${DBVERSION_MAJOR_MINOR}" != "8.0" ]
then
    EXITCODE=$TEMPFILES_ARE_AVAILABLE
else
    EXITCODE=$TEMPFILES_NOT_AVAILABLE
fi

exit $EXITCODE
