#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  runningdbs
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       26-Mar-2004     1.0     oracle    Original version
#
#+++___________________________________________________________________________________


. /opt/dsp/env/dsp.env
. ${CS_TOP}/env/funcs.sh


#
# Script starts here
#
#
#set_error_trap

#long listing
LONG=NO

function usage
{
echo usage
exit 1
}

while getopts ':l' OPTION ${*}
do
    case "$OPTION" in
        l) LONG=YES ;;
        \?) usage ;;
        \:) usage ;;
    esac
done

#
# the square brackets around smon to prevent
# the grep showing up in the list
# 
# oracle documemntation suggests _$# are valid characters
# in a SID.  Why anyone would choose these is beyond me
# however lets grep for them anyway.  Would be interesting
# to see how a sid starting with a # would be depicted
# in /etc/oratab without it being interpreted as a comment
# Without testing it I have doubts whether a SID starting
# with a character that isn't alphanumer (ie. a-zA-Z0-9) 
# would be allowed
#
# ignore any with leading + as likely ASM
if [ "${LONG}" = "NO" ]
then
    ps -ef | grep 'ora_smon_[a-zA-Z0-9_$#]' | awk '{print $NF}' | cut -d_ -f3 | sort
else
    ps -ef | grep 'ora_smon_[a-zA-Z0-9_$#]' | awk '{print $NF ":" $1 ":" $2}' | sed -e 's/^ora_smon_'// | sort
fi



exit $EXITCODE

