#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  runremotedbs
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       23-Jul-2004     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

#
# Script starts here
#
#
set_error_trap

runallhosts $(which runalldbs) "${*}"
EXITCODE=$?

exit $EXITCODE

