#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  show_info_about_archlog
#
# Description:			Generate a CREATE CONTROFILE script to standard output
#
# Parameters:			1	(optional)	SID
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       14-Jan-2004     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING="[-d SID] log_sequence"



if [ $# -gt 3 ]
then
    usage
fi

if [ "$1" = "-d" ]
then
    export ORACLE_SID=$(echo ${2} | awk -F: '{print $1}')

    whichhost=$(echo ${2} | awk -F: '{print $2}' | tr "[:upper:]" "[:lower:]")

    if [ "${whichhost}" = "" ] || [ "${whichhost}" = "${HOSTNAME}" ]
    then
        whichhost=${HOSTNAME}

        if chkoradbinoratab ${ORACLE_SID}
        then
            :
        else
            echo "ERROR: ${ORACLE_SID} not in oratab"
            EXITCODE=1
            exit ${EXITCODE}
        fi

        . /usr/local/bin/oraenv 2>&1 > /dev/null
    fi

    shift
    shift
else
    whichhost=${HOSTNAME}
fi

if [ $# -ne 1 ]
then
    usage
fi

LOGSEQ=${1}

if [ "${ORACLE_SID}" = "" ]
then
    echo ERROR: ORACLE_SID not set
    exit 1
fi


if [ "$whichhost" = "${HOSTNAME}" ]
then
    if chkorainstsysdba ${ORACLE_SID}
    then
        :
    else
        echo ERROR: ${ORACLE_SID} is not up
        exit 1
    fi


sqlplus -s ${SQLPLUS_DBA_LOGON} << *EOF* 2>&1
whenever sqlerror exit 4
set pages 0
set lines 500
set feedback off
col INFO format a160
select 'logseq#=' || sequence# || ': first_scn=' ||
       to_char(first_change#) || ' [' ||
       to_char(first_time, 'YYYY-MON-DD:HH24:MI:SS') || '] last_scn=' ||
       to_char(next_change#) || ' [' ||
       to_char(next_time, 'YYYY-MON-DD:HH24:MI:SS') || ']' INFO
from v\$archived_log
where sequence# = ${LOGSEQ}
  and standby_dest != 'YES'
exit
*EOF*
status=$?

if [ $status -ne 0 ]
then
    echo ERROR: Encountered error when running $EXECUTABLE
    EXITCODE=1
fi

else
    runremotecmd ${whichhost} $(which ${scriptname}) -d ${ORACLE_SID} ${LOGSEQ}
    status=$?

      if [ $status -ne 0 ]
      then
          echo "ERROR: Encountered error running remote command"
          EXITCODE=1
      fi
fi

exit $EXITCODE

