
create profile unlimited_profile limit
FAILED_LOGIN_ATTEMPTS            UNLIMITED
PASSWORD_LIFE_TIME               UNLIMITED
PASSWORD_REUSE_TIME              UNLIMITED
PASSWORD_REUSE_MAX               UNLIMITED
PASSWORD_LOCK_TIME               UNLIMITED
PASSWORD_GRACE_TIME              UNLIMITED
INACTIVE_ACCOUNT_TIME            UNLIMITED
PASSWORD_VERIFY_FUNCTION	 NULL
;
