CREATE PROFILE NOEXPIRE LIMIT
   COMPOSITE_LIMIT            UNLIMITED
   SESSIONS_PER_USER          UNLIMITED
   CPU_PER_SESSION            UNLIMITED
   CPU_PER_CALL               UNLIMITED
   LOGICAL_READS_PER_SESSION  UNLIMITED
   LOGICAL_READS_PER_CALL     UNLIMITED
   IDLE_TIME                  UNLIMITED
   CONNECT_TIME               UNLIMITED
   PRIVATE_SGA                UNLIMITED
   FAILED_LOGIN_ATTEMPTS      UNLIMITED
   PASSWORD_LIFE_TIME         UNLIMITED
   PASSWORD_REUSE_TIME        UNLIMITED
   PASSWORD_REUSE_MAX         UNLIMITED
   PASSWORD_VERIFY_FUNCTION   ORA12C_STRONG_VERIFY_FUNCTION;
