#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:          	bkup
#
# Description:         	 	Backup file/directory with .YYYYMMDD suffix
#
# Parameters:
#
# Environment:
#
# Modification history:
#
#	16-Feb-2003	1.0	oracle	Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

EXITCODE=0
USAGE_STRING="file1 [file2 file3 ...]"


if [ $# -lt 1 ]
then
    usage
fi

now=$(date +%Y%m%d)

if [ "${now}" = "" ]
then
    echo "ERROR: date command does not seem to work - manual/alternate backup required - exiting"
    EXITCODE=1
    exit ${EXITCODE}
fi

for filename in ${*}
do
    if [ -f $filename -o -d $filename ]
    then
        bkupfilename=${filename}.$(date +%Y%m%d)
        [ -f ${bkupfilename} ] && bkupfilename=${filename}.$(date +%Y%m%d_%H%M)
        [ -f ${bkupfilename} ] && bkupfilename=${filename}.$(date +%Y%m%d_%H%M%S)
        [ -f ${bkupfilename} ] && bkupfilename=${filename}.$(date +%Y%m%d_%H%M%S).${$}

        while [ -f ${bkupfilename} ]
        do
            bkupfilename=${bkupfilename}.${$}
        done        

        cp -rp ${filename} ${bkupfilename}
	status=$?

	if [ $status -ne 0 ]
	then
		echo error: could not copy $filename to $filename.$today
		EXITCODE=1
	fi

        echo
        ls -ald $filename
        ls -ald ${bkupfilename}
        echo
    else
	echo "ERROR: $filename not a regular file or directory - exiting"
	EXITCODE=2
        exit ${EXITCODE}
    fi
done

exit $EXITCODE
