#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  containsip
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       30-Jan-2004     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING="file"
WARN_ON_NONZERO_EXIT="NO"

#
# Script starts here
#
#
#set_error_trap

if [ $# -ne 1 ]
then
    usage
else
    file=$1
fi

if grep '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*[!\.]' $file 2>&1 > /dev/null
then
    EXITCODE=0
else
    EXITCODE=1
fi

exit $EXITCODE

