#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  dubysize
#
# Description:			Run du and sort by size
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       02-Aug-2007     1.0     root    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING=""


#
# Define local script variables
#

#
# Script starts here
#
#
set_error_trap

du -sk ${*} | sort -h



exit $EXITCODE

