#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  extractip
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       30-Jan-2004     1.0     oracle    Original version
#
#+++___________________________________________________________________________________


. /opt/dsp/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING="file"

#
# Script starts here
#
#
#set_error_trap

if [ $# -ne 1 ]
then
    usage
else
    file=${1}
fi

if [ ! -r $file ]
then
    echo ERROR: $file not readable
    exit 1
else
    grep '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]' $file
fi

exit $EXITCODE

