#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  findtoday
#
# Description:			Find files modified in last 24hrs
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       15-Apr-2004     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING="[dir(s)]"


#
# Script starts here
#
#
set_error_trap

DIR="."
if [ $# -gt 0 ]
then
    DIR=${*}
fi

find ${DIR} -mtime -1



exit $EXITCODE

