#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:          	findlinks
#
# Description:          	Find symbolic links
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#	13-Jun-2003	1.0	oracle	Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh


USAGE_STRING="[dir]"

if [ $# -gt 1 ]
then
    usage
fi

if [ $# -eq 1 ]
then
    searchdir=$1
else 
    searchdir="."
fi

find $searchdir -type l -exec ls -ald {} \;


exit $EXITCODE

