#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:          	findtext
#
# Description:          	Find files with matching file extension(s)
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#	13-Jun-2003	1.0	oracle	Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING="extensions(s)"
searchstring=""

if [ $# -eq 0 ]
then
    usage
fi

for string in $*
do
    searchstring=$searchstring\|$string
done

echo [Searching for: $(echo $searchstring | cut -c2-)]
searchstring=$(echo $searchstring | cut -c2-)

find . -type f -exec file {} \; | grep -i text | cut -d: -f1 | xargs -i egrep -i -l "${searchstring}" {}

exit $EXITCODE

