#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  finddays
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       13-Oct-2008     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING=""


#
# Define local script variables
#

#
# Script starts here
#
#
set_error_trap

find . -type f -mtime -${1}



exit $EXITCODE

