#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  getmypubip
#
# Description:			Show public IP address
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       29-Mar-2004     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh


#
# Script starts here
#
#
set_error_trap


dig +short myip.opendns.com @resolver1.opendns.com

