#!/bin/bash 
#+++___________________________________________________________________________________
#
#
# Script name:          	listeningports
#
# Description:          	Show output of netstat -aln
#
# Parameters:
#
# Environment:
#
# Modification history:
#
#	DD-MON-YYYY	1.0	oracle	Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING=""


if [ $# -gt 0 ]
then
    usage
fi

netstat -aln
