#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                 listrljob
#
# Description:			Directory listing of runlater jobs
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       22-Jul-2004     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING="[jobid]"
WARN_ON_NONZERO_EXIT="NO"

#
# Script starts here
#
#set_error_trap

if [ $# -gt 1 ]
then
    usage
fi

ls -1trd ${HOME}/DSP/runlater/out/*.out 

exit $EXITCODE

