#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:          	XXSCRIPT_NAMEXX
#
# Description:          
#
# Parameters:
#
# Environment:
#
# Modification history:
#
#	DD-MON-YYYY	1.0	oracle	Original version
#
#+++___________________________________________________________________________________

. /opt/dsp/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING=""


if [ $# -gt 0 ]
then
    usage
fi

netstat -aln
