#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:          	newshfull
#
# Description:          	Create new shell script
#
# Parameters:
#
# Environment:
#
# Modification history:
#
#	DD-MON-YYYY	1.0	oracle	Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh


modhist=$(date +%d-%b-%Y)

if [ $# -lt 1 ]
then
    echo usage: ${scriptname} file1 [file2, file3, ...]
    exit 1
fi

for newscript in ${*}
do
 if [ -f $newscript ]
 then
     echo error: $newscript exists
     EXITCODE=1
 else
    cp $CS_TOP/templates/sh.full.template ${newscript}
    status=$?

    if [ $status -ne 0 ]
    then
	echo error: could not create script ${newscript}
	EXITCODE=1
    else
	chmod ug+x,u+w ${newscript}
	status=$?

	if [ $status -ne 0 ]
	then
	    echo error: could not chmod script ${newscript}
	    EXITCODE=1
	else
	    replace XXSCRIPT_NAMEXX ${newscript} ${newscript}
	    replace DD-MON-YYYY ${modhist} ${newscript}
	    replace  xxxuseridxxx ${thisuser} ${newscript}
	    status=$?

	    if [ $status -ne 0 ]
	    then
		echo error: could not replace new script ${newscript}
		EXITCODE=1
	    else
		vi ${newscript}
	    fi
	fi
    fi
 fi
done
