#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:          	pause
#
# Description:          	Send process SIGSTOP to process
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#	13-Mar-2003	1.0	oracle	Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING="PID"

if [ $# -ne 1 ]
then
    usage
else
    PID=${1}
fi

kill -SIGSTOP ${PID}

exit $EXITCODE

