#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  renamefile
#
# Description:			Rename file(s) using pattern matching and search/replace
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       25-Sep-2003     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh



#
# Script starts here
#
#
set_error_trap

if [ $# -lt 3 ]
then
   echo "usage: $scriptname string1 string2 file(s)"
   exit 1
fi

string1=${1}
string2=${2}

shift;shift

for filename in ${*}
do
    if [ -f ${filename} ]
    then
        newfilename=$(echo $filename | sed -e "s/$string1/$string2/g")
        mv $filename $newfilename 
    else
	:
    fi
done


exit $EXITCODE

