#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:          	resume
#
# Description:          
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#	13-Mar-2003	1.0	oracle	Original version
#
#+++___________________________________________________________________________________

. /opt/dsp/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING="PID"

if [ $# -ne 1 ]
then
    usage
fi

kill -SIGCONT $1

exit $EXITCODE

