#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  runhosts
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       23-Jul-2004     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

. /opt/dsp/env/dsp.env
. ${CS_TOP}/env/funcs.sh



#
# Script starts here
#
#
set_error_trap

if [ $# -lt 1 ]
then
    usage
fi

for HOST in $(grep -v ^# ${CS_TOP}/config/hosts)
do
    echo "###############################################################################################"
    echo "#"
    echo "#                     host=${HOST}"
    echo "#"
    echo "###############################################################################################"
    echo

    runremotecmd ${HOST} "${*}"
    status=$?

      if [ $status -ne 0 ]
      then
	  echo "ERROR: Encountered error for ${HOST}"
	  EXITCODE=1
      fi

    echo
done


exit $EXITCODE

