#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  runtoday
#
# Description:			Run a command, as passed by command line, for the current
#				day (ie. until midnight) with intervals of 1 minutes 
#				between executions
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       26-Sep-2003     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

. /opt/dsp/env/dsp.env
. ${CS_TOP}/env/funcs.sh

#
# Script starts here
#
#
set_error_trap

thisday=$(date +%d)
currday=${thisday}

while [ "$currday" = "$thisday" ]
do
    currday=$(date +%d)
    ${*}
    sleep 60
done

exit $EXITCODE

