#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  runtoday
#
# Description:			Run a command every minute for the current day only
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       26-Sep-2003     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

#
# Script starts here
#
#
set_error_trap

thisday=$(date +%d)
currday=${thisday}

while [ "$currday" = "$thisday" ]
do
    currday=$(date +%d)
    ${*}
    sleep 60
done

exit $EXITCODE

