#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  serverinfo2
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       02-Aug-2025     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING=""

# server info
# Oracle Grid
# Oracle Database
	# Oracle Homes
        # Oracle DB#1
#		CDB$ROOT
#		PDB01
#		PDB02
        # Oracle DB#2
#                CDB$ROOT
#                PDB01
#                PDB02
		


# hostnamme
# dspserverid
# machine-id
# host-id
# server type
# db hosting
# os release
# os kernel
# uptime
# last boot
# load avgs
# memory
# ip addresses
# mac addresses
# server time

# #vCPUs
# memory
# 

# oracle database homes
	location
	version
	patch-levels
	edition
# oracle databases
	SID
	name
	oracle_home
	version
	edition
#

#
# Define local script variables
#

#
# Script starts here
#
#
set_error_trap



exit $EXITCODE

