#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  showpath
#
# Description:			Show directories in $PATH one per line
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       29-Mar-2004     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh


#
# Script starts here
#
#
set_error_trap

echo $PATH | sed 's/:/ /g' | xargs -n1 echo

exit $EXITCODE

