#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  showmacaddr
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       27-Jul-2025     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING=""


#
# Define local script variables
#

#
# Script starts here
#
#
set_error_trap

ip link | awk '$1~/^[0-9]*:/{printf "%s ", $2} /^ /{print $2}'




exit $EXITCODE

