#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  showipaddrs
#
# Description:
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       28-Jul-2025     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

USAGE_STRING=""


#
# Define local script variables
#

#
# Script starts here
#
#
ip_addrs=$(hostname -I 2>/dev/null)
status=$?

if [ $status -ne 0 ]
then
    ip_addrs=$(hostname -i 2>/dev/null)
    status=$?

    if [ $status -ne 0 ]
    then
        EXITCODE=1
    fi
fi

if [ "${ip_addrs}" != "" ]
then
    echo ${ip_addrs} | xargs -n 1
fi


exit $EXITCODE

