#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:          timertest
#
# Description:		A simple benchmark test for CPU
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       09-Oct-2003     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

typeset -i x
typeset -i y

x=1
y=1

MAX=10

echo "Starting test..."

time (
while [ $y -lt ${MAX} ]
do
    echo "Loop ${y} of ${MAX}..."
    while [ $x -lt 200000 ]
    do
        let x=x+1
    done
    x=0
    let y=y+1
done
)
