#!/bin/bash

#+++___________________________________________________________________________________
#
#
# Script name:                  whatisrunning
#
# Description:			Attempt to determine main software running on server based on ps
#
# Parameters:
#
# Environment:
#
# Return codes:
#
# Modification history:
#
#       15-Apr-2004     1.0     oracle    Original version
#
#+++___________________________________________________________________________________

### BEGIN NOT YET IMPLEMENTED
# Oracle Access Manager (OAM)
# Oracle Enterprise Manager (OEM)
# Oracle OC4J
# Veritas Netbackup Veeam commvault
### END-NOT YET IMPLEMENTED

CS_TOP=${CS_TOP:-/opt/dsp}
. ${CS_TOP}/env/dsp.env
. ${CS_TOP}/env/funcs.sh

DEL_TEMPFILES="NO"

function ps_search
    {
    searchstring=""

    for i in ${*}
    do
        if [ "${searchstring}" = "" ]
        then
            searchstring=${i}
        else
            searchstring="${searchstring}|${i}"
        fi
    done

    grep -i -E "${searchstring}" ${tmpfile}.ps-aux 2>&1 > /dev/null
    status=$?

    return $status
    }

#
# Script starts here
#
#
set_error_trap

ps -aux > ${tmpfile}.ps-aux

FOUND_ONE="NO"

echo ""
echo "****************************************************************************"
echo "                             IMPORTANT"
echo "****************************************************************************"
echo "This is not an exact or guaranteed output.  The list of (if any) software or"
echo "components shown is based only on pattern matching against output of the"
echo "ps command.  Please consider the POSSIBILITY of FALSE POSITIVES and software"
echo "may be installed and running that this script has not been configured to"
echo "identity.  This output should be considered with healthy scepticism.  Please"
echo "help maintain this script by informing the code maintainer of any software"
echo "you believe it has not correctly detected."
echo "****************************************************************************"
echo ""

# Oracle Grid

if ps_search grid ohasd +asm
then
    echo "Oracle Grid Infrastructure"
    FOUND_ONE="YES"
fi


# Oracle Database

if ps_search ora_lgwr_ ora_smon_
then
    echo "Oracle Database"
    FOUND_ONE="YES"
fi

# Oracle Listener

if ps_search tnslsnr
then
    echo "Oracle Listener"
    FOUND_ONE="YES"
fi

# Oracle WebLogic

if ps_search weblogic
then
    echo "Oracle WebLogic"
    FOUND_ONE="YES"
fi

# Oracle Forms

if ps_search wls_forms
then
    echo "Oracle Forms"
    FOUND_ONE="YES"
fi

# Oracle Reports

if ps_search wls_reports
then
    echo "Oracle Reports"
    FOUND_ONE="YES"
fi

# Oracle Application Server

if ps_search opmn
then
    echo "Oracle Application Server"
    FOUND_ONE="YES"
fi

# Oracle MySQL

if ps_search mysql
then
    echo "Oracle MySQL"
    FOUND_ONE="YES"
fi

# Oracle ORDS

if ps_search ords
then
    echo "Oracle REST Data Services (ORDS)"
    FOUND_ONE="YES"
fi

# Oracle E-Business

if ps_search FNDSM FFTM RCVOLTM POXCON INTCM FNDCRM PALIBR MRCLIB FNDLIBR INVLIBR oacore_server ofm_server
then
    echo "Oracle E-Business (concurrent managers)"
    FOUND_ONE="YES"
fi


# DBvisit

if ps_search dbv
then
    echo "DBvisit"
    FOUND_ONE="YES"
fi

# Apache/Oracle HTTP Server

if ps_search httpd
then
    echo "HTTP Server (Apache/Oracle/RedHat etc.)"
    FOUND_ONE="YES"
fi

# NGINX

if ps_search nginx
then
    echo "nginx"
    FOUND_ONE="YES"
fi

# Apache tomcat
#

if ps_search tomcat
then
    echo "Apache Tomcat"
    FOUND_ONE="YES"
fi


# postgreSQL

if ps_search postgresql
then
    echo "PostgreSQL"
    FOUND_ONE="YES"
fi

# RedHat jboss


if ps_search jboss
then
    echo "Red Hat jBoss"
    FOUND_ONE="YES"
fi

# IBM WebSphere

if ps_search websphere
then
    echo "IBM WebSphere"
    FOUND_ONE="YES"
fi

# IBM db2

if ps_search db2
then
    echo "IBM DB2"
    FOUND_ONE="YES"
fi


# DSP UIM monitoring - nimbus / nimsoft

if ps_search nimsoft nimbus
then
    echo "DSP UIM Monitoring"
    FOUND_ONE="YES"
fi


# P6 Primavera

if ps_search p6 primavera
then
    echo "P6 Primavera"
    FOUND_ONE="YES"
fi

# JDE

if ps_search jde
then
    echo "JDE"
    FOUND_ONE="YES"
fi

# splunk

if ps_search splunk
then
    echo "Splunk"
    FOUND_ONE="YES"
fi

# qualys

if ps_search qualys
then
    echo "Qualys"
    FOUND_ONE="YES"
fi

# Crowdstrike

if ps_search crowdstrike falcon-sensor
then
    echo "Crowdstrike"
    FOUND_ONE="YES"
fi

# clamav

if ps_search clamav
then
    echo "Clamav"
    FOUND_ONE="YES"
fi

# kubernetes

if ps_search k8 kubectl kube
then
    echo "Kubernetes"
    FOUND_ONE="YES"
fi

# docker

if ps_search k8 docker
then
    echo "Docker"
    FOUND_ONE="YES"
fi


#
#------ -------------- end of section performing checks ----------------------
#

if [ "${FOUND_ONE}" = "NO" ]
then
    echo "<none>"
fi
echo


exit $EXITCODE

